### ISSUE TITLE
📍 QUESTS PARA O DIA 19/03 📆 

### ISSUE THREAD

**Issue by alaudee** [alaudee/T.A.R.S#2]
*ENTRAR NA PARTIDA*
- [x] Tratar erro ao entrar na partida (lembrar do retorno da função para entrar na partida)
- [x] Validar se um mesmo jogador está tentando criar um login duas vezes
- [x] Mostrar os dados retornados na tela, quando entrar na partida

**Comment by FelipeJun** [comment]
1 - Christopher
2 - Otávio
3 - João
