### ISSUE TITLE
QUESTS DO DIA 09/04 📆 

### ISSUE THREAD

**Issue by alaudee** [alaudee/T.A.R.S#3]
- [ ] Verificar se é sua vez
- [ ] Rolar o dado e mostrar os valores resultantes dos dados 🎲 
- [ ] Chamar o tabuleiro e representar graficamente o estado do tabuleiro na tela, com as posições dos alpinistas e das bases, respeitando as cores de cada jogador.

**Comment by FelipeJun** [comment]
![image](https://user-images.githubusercontent.com/61765247/111874747-5bd81980-8975-11eb-9a4f-6e8ad05e568d.png)
Imagem mostrando como é o tabuleiro no banco de dados.

**Comment by FelipeJun** [comment]
![1](https://user-images.githubusercontent.com/61765247/111908271-580ccb80-8a37-11eb-9130-2b03dd661bb6.PNG)
